name: Build and test rules

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - id: install
        name: Install dependencies
        run: yarn install --frozen-lockfile

      - id: test
        name: Compile and test
        run: yarn test

      - name: Run pkg.pr.new
        run: |
          yarn compile
          npx pkg-pr-new publish --packageManager=yarn
